apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: development
  name: file-storage-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: development
  name: postgres-storage-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi