apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
  - image: postgres
    context: postgres
    sync:
      manual:
      - src: "**/*.sql"
        dest: .
    docker:
      dockerfile: Dockerfile.dev
  # - image: admin
  #   context: admin
  #   sync:
  #     manual:
  #     - src: 'src/**/*.js'
  #       dest: .
  #     - src: 'src/**/*.jsx'
  #       dest: .
  #     - src: 'package.json'
  #       dest: .
  #     - src: 'public/**/*.html'
  #       dest: .
  #     - src: 'src/assets/sass/**/*.scss'
  #       dest: .
  #     - src: 'src/build/**/*.js'
  #       dest: .
  #   docker:
  #     dockerfile: Dockerfile.dev
  # - image: api
  #   context: api
  #   sync:
  #     manual:
  #     - src: "**/*.py"
  #       dest: .
  #   docker:
  #     dockerfile: Dockerfile.dev
  # - image: client
  #   context: client
  #   sync:
  #     manual:
  #     - src: 'src/**/*.js'
  #       dest: .
  #     - src: 'src/**/*.jsx'
  #       dest: .
  #     - src: 'package.json'
  #       dest: .
  #     - src: 'public/**/*.html'
  #       dest: .
  #     - src: 'src/assets/sass/**/*.scss'
  #       dest: .
  #     - src: 'src/build/**/*.js'
  #       dest: .
  #   docker:
  #     dockerfile: Dockerfile.dev
  local:
    push: false
deploy:
  kubectl:
    manifests:
      - k8s/ingress/dev.yaml 
      - k8s/postgres/dev.yaml
      # - k8s/admin/dev.yaml
      # - k8s/client/dev.yaml
      # - k8s/api/dev.yaml
