apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-dev
  namespace: development
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: api
          ports:
            - containerPort: 5000
          env:
            - name: PGUSER
              value: dev_user
            - name: PGHOST
              value: postgres-cluster-ip-service-dev
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: k8s_tut_dev
            - name: PGPASSWORD
              value: password12345
          volumeMounts:
            - mountPath: /mnt/file-storage
              name: file-storage-dev
              subPath: file-storage
      volumes:
        - name: file-storage-dev
          persistentVolumeClaim:
            claimName: file-storage-dev
---
apiVersion: v1
kind: Service
metadata:
  name: api-cluster-ip-service-dev
  namespace: development
spec:
  type: ClusterIP
  selector:
    component: api
  ports:
    - port: 5000
      targetPort: 5000
