apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment-dev
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      component: admin
      environment: development
  template:
    metadata:
      labels:
        component: admin
        environment: development
    spec:
      containers:
        - name: admin
          image: admin
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: admin-cluster-ip-service-dev
spec:
  type: ClusterIP
  selector:
    component: admin
    environment: development
  ports:
    - port: 4000
      targetPort: 4000