apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: development
  name: postgres-deployment-dev
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:11-alpine
          ports:
            - containerPort: 5432
          env: 
            - name: POSTGRES_DB
              value: k8s_tut_dev
            - name: POSTGRES_USER
              value: dev_user
            - name: POSTGRES_PASSWORD
              value: password12345
            - name: POSTGRES_INITDB_ARGS
              value: "-A md5"
            - name: PGDATA
              value: /var/postgresql/data
          volumeMounts:
            - name: postgres-storage-dev
              mountPath: /var/postgresql
      volumes:
        - name: postgres-storage-dev
          persistentVolumeClaim:
            claimName: postgres-storage-dev
---
apiVersion: v1
kind: Service
metadata:
  namespace: development
  name: postgres-cluster-ip-service-dev
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - port: 5432
      targetPort: 5432